version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_matriculas
    restart: always
    environment:
      MYSQL_DATABASE: matriculas_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3308"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: app_matriculas
    restart: always
    ports:
      - "3307:3307"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/matriculas_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: